apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qsjcoip3k-python 
  janus-idp.io/tekton: qsjcoip3k-python
  backstage.io/kubernetes-id: qsjcoip3k-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qsjcoip3k-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml