apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: qsjcoip3k-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qsjcoip3k-python 
  name: qsjcoip3k-python
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: qsjcoip3k-python
    weight: 100 
